### ISSUE TITLE
Failure to run test

### ISSUE THREAD

**Issue by hate5six** [Lambda-3/PyCobalt#1]
I'm trying to follow the installation instructions but I'm running into a problem. I have a CoreNLP server running on port 9000, and also PyCobalt on 5128. 

When I run
`curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -d '{"text": "Donald Trump is the president of USA. He is a business man."}' "http://localhost:5128/resolve/text"`

I get:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

```
The console running PyCobalt displays:

```
[2017-06-06 16:12:59,555] ERROR in app: Exception on /resolve/text [POST]
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "service.py", line 29, in resolve_text
    substituted = substitute(*resolve(text, ''))
  File "./pycobalt/resolving.py", line 50, in resolve
    sentences: List[Sentence] = annotate_text(text)
  File "./pycobalt/language/stanford_tools.py", line 21, in annotate_text
    )['sentences']
TypeError: string indices must be integers
[pid: 20300|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 347 bytes} [Tue Jun  6 16:12:59 2017] POST /resolve/text => generated 291 bytes in 28 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)

```

Has something changed to cause the test example to fail?

**Comment by bermeitinger-b** [comment]
I can not reproduce this issue. I tested inside docker-compose and running it `PYCOBALT_CORENLP=http://localhost:9000 python service.py` (with CoreNLP running at port 9000).

Your `TypeError` occurs when reading the value that the `pycorenlp` wrapper for the CoreNLP service returns. 
Can you look inside the return value in [pycobalt/language/stanford_tools.py
](../blob/master/pycobalt/language/stanford_tools.py#L15) with a debugger or simply printing the variable `annotations` before accessing it as a dict? It seems that the response from your CoreNLP server is not a dictionary.

Or can you check the log from the CoreNLP server?

**Comment by hate5six** [comment]
Looks like there was a missing CoreNLP model causing it to crash. Test ran smoothly. Thanks!
